#define VIAL_KEYBOARD_UID {0x0A, 0xA3, 0x01, 0x10, 0x46, 0x68, 0xAD, 0xC2}

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP28
#define I2C1_SCL_PIN GP29

#define ENCODER_A_PINS { GP27 }
#define ENCODER_B_PINS { GP26 }
#define ENCODER_RESOLUTION 2
#define ENCODER_DEFAULT_POS 3
#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define WS2812_DI_PIN GP24
#define RGB_MATRIX_LED_COUNT 12

#define BOOTMAGIC_ROW 1
#define BOOTMAGIC_COLUMN 0

#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61

#define QUANTUM_PAINTER_DISPLAY_TIMEOUT	0
#define RGB_MATRIX_SLEEP

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

#define OLED_BRIGHTNESS 255
